name: MacOS, gcc

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        run: brew install automake libtool help2man texinfo libiconv
      - name: Build
        run: |
          export LDFLAGS="-L/opt/homebrew/opt/libiconv/lib"
          export CPPFLAGS="-I/opt/homebrew/opt/libiconv/include"
          ./autogen.sh
          make -j4
      - name: Test
        run: make check
